<?php

namespace Container1AalPKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6JA4lu7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6JA4lu7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6JA4lu7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mg' => ['services', 'doctrine', 'getDoctrineService', false],
            'request' => ['privates', '.errored.CfJvZh1', NULL, 'Cannot determine controller argument for "App\\Controller\\BaseController::order()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".'],
        ], [
            'mg' => '?',
            'request' => '?',
        ]);
    }
}
