<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKq5QrJd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKq5QrJd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKq5QrJd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKq5QrJd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKq5QrJd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kq5QrJd',
    'container.build_id' => '87786530',
    'container.build_time' => 1655295095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKq5QrJd');
