<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1AalPKI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1AalPKI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1AalPKI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1AalPKI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1AalPKI\App_KernelDevDebugContainer([
    'container.build_hash' => '1AalPKI',
    'container.build_id' => '27d5e272',
    'container.build_time' => 1655212095,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1AalPKI');
